config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path , include

from main import views

app_name = 'api'

urlpatterns = [
    path('', views.companies_view),
    path('add_Employee/<int:company_id>/', views.add_employee, name='add_Employee'),
    path('select2/', include('django_select2.urls')),
]

main/models.py
from django.db import models


class Employee(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    comment = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Company(models.Model):
    name = models.CharField(max_length=100)


class Emp_company(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE) 
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.company.name} {self.employee.first_name}"

main/forms.py
from .models import Emp_company
from django.forms import ModelForm 
from django import forms

class EmployeeAssociationForm(ModelForm):
    class Meta:
        model = Emp_company
        fields = ['employee']
    
    def clean(self):
        cleaned_data = super().clean()
        employee = cleaned_data.get('employee')
        company = cleaned_data.get('company')

        # Check if the employee is already associated with another company
        if Emp_company.objects.filter(employee=employee).exclude(company=company).exists():
            raise forms.ValidationError('This employee is already associated with another company.')

        return cleaned_data

main/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from main.models import Company , Employee , Emp_company
from .forms import EmployeeAssociationForm
from django.forms import ModelForm
# Create your views here.


def companies_view(request):
    return render(request, 'companies.html', {"companies": Company.objects.all()})

def add_employee(request, company_id):
    company = Company.objects.get(pk=company_id)
    employee = Employee.objects.all()
    if request.method == 'POST':
        form = EmployeeAssociationForm(request.POST)
        if form.is_valid():
            employee = form.cleaned_data['employee']
            Emp_company.objects.create(company=company, employee=employee)
            return redirect('/')
    else:
        form = EmployeeAssociationForm()

    return render(request, 'add_employee.html', {'form': form, 'company': company ,'employee':employee})

templates/add_employee.html
<html>
<head>   
<title>Associate Employee </title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <datalist id="employee-list">
            {% for employee in employee %}
                <option value="{{ employee }}">{{ employee }}</option>
            {% endfor %}
        </datalist>


        <button type="submit">Add Employee to Company</button>
    </form>
    </body>
    <script>
      
         document.addEventListener('DOMContentLoaded', function () {
     
        const employeeInput = document.querySelector('#id_employee');
        const employeeDatalist = document.querySelector('#employee-list');

        employeeInput.addEventListener('input', function () {
            const inputValue = employeeInput.value.toLowerCase();
            const options = employeeDatalist.querySelectorAll('option');

            options.forEach(function (option) {
                const optionValue = option.value.toLowerCase();
                if (optionValue.includes(inputValue)) {
                    option.style.display = 'block';
                } else {
                    option.style.display = 'none';
                }
            });
        });
    });

    </script>
    </html>

templates/companies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Companies List</title>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 70%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>
<body>
<table>
    <tr>
        <th style="width: 20%;">Company</th>
        <th>Employees</th>
    </tr>
    {% for company in companies %}
    <tr>
        <td>{{ company.name }} <a href="add_Employee/{{ company.id }}/">(Add Employee)</a></td>
        <td>
            {% for emp_company in company.emp_company_set.all %}
                {{ emp_company.employee.first_name }} {{ emp_company.employee.last_name }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </td>
    </tr>
    {% endfor %}
</table>
</body>
</html>